---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4906048071-Omsme6tzeP69NSm2aoLF0ONbjDT743GrrMasqm3
:access_token_secret: uW8bPVU3I8xQs9xq6Aj8dQZgYJkjgaUAIANRuALF7xLH1
